apiVersion: batch/v1
kind: Job
metadata:
  name: configure-cert-manager
  namespace: cert-manager
spec:
  template:
    spec:
      serviceAccountName: helm-cert-manager
      restartPolicy: Never
      containers:
      - name: kubectl
        image: bitnami/kubectl:1.28
        command:
        - /bin/sh
        - -c
        - |
          echo "Waiting for cert-manager webhooks to be ready..."
          kubectl wait --for=condition=available --timeout=300s deployment/cert-manager-webhook -n cert-manager
          sleep 10
          
          echo "Creating ClusterIssuers..."
          cat <<EOF | kubectl apply -f -
          apiVersion: cert-manager.io/v1
          kind: ClusterIssuer
          metadata:
            name: letsencrypt-prod
          spec:
            acme:
              server: https://acme-v02.api.letsencrypt.org/directory
              email: devops@rbccoach.com
              privateKeySecretRef:
                name: letsencrypt-prod
              solvers:
              - http01:
                  ingress:
                    class: nginx
          ---
          apiVersion: cert-manager.io/v1
          kind: ClusterIssuer
          metadata:
            name: letsencrypt-staging
          spec:
            acme:
              server: https://acme-staging-v02.api.letsencrypt.org/directory
              email: devops@rbccoach.com
              privateKeySecretRef:
                name: letsencrypt-staging
              solvers:
              - http01:
                  ingress:
                    class: nginx
          EOF
          
          echo "ClusterIssuers created successfully"