extends: default

rules:
  line-length:
    max: 150
    level: warning
  comments:
    min-spaces-from-content: 1
  indentation:
    spaces: 2
    indent-sequences: true
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']

ignore: |
  .github/
  argocd/install/argocd-install.yaml