apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm-nginx-ingress
  namespace: ingress-nginx
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: helm-nginx-ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: helm-nginx-ingress
  namespace: ingress-nginx
---
apiVersion: batch/v1
kind: Job
metadata:
  name: install-nginx-ingress
  namespace: ingress-nginx
spec:
  template:
    spec:
      serviceAccountName: helm-nginx-ingress
      restartPolicy: Never
      containers:
      - name: helm
        image: alpine/helm:3.13.0
        command:
        - /bin/sh
        - -c
        - |
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo update
          helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \
            --namespace ingress-nginx \
            --create-namespace \
            --values /config/values.yaml \
            --wait \
            --timeout 5m
        volumeMounts:
        - name: values
          mountPath: /config
      volumes:
      - name: values
        configMap:
          name: nginx-ingress-values
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-values
  namespace: ingress-nginx
data:
  values.yaml: |
    controller:
      replicaCount: 1
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi
      service:
        type: LoadBalancer
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-sku: "Basic"
      config:
        use-forwarded-headers: "true"
        compute-full-forwarded-for: "true"
        proxy-body-size: "10m"
      ingressClassResource:
        name: nginx
        enabled: true
        default: true
    defaultBackend:
      enabled: false