apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: leasing-app-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: leasing-app
    environment: staging
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/rbc-infrastructure
    targetRevision: main
    path: kubernetes/apps/leasing-app/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: leasing-app-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
    managedNamespaceMetadata:
      labels:
        environment: staging
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
  info:
    - name: "Description"
      value: "Staging environment for RBC Leasing Application"
    - name: "Owner"
      value: "QA Team"