apiVersion: apps/v1
kind: Deployment
metadata:
  name: leasing-app-backend
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: backend
        env:
        - name: NODE_ENV
          value: "staging"
        - name: LOG_LEVEL
          value: "info"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: leasing-app-frontend
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: frontend
        env:
        - name: VITE_API_URL
          value: "https://api-staging.yourdomain.com/api"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"