apiVersion: apps/v1
kind: Deployment
metadata:
  name: leasing-app-backend
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: backend
        env:
        - name: NODE_ENV
          value: "development"
        - name: LOG_LEVEL
          value: "debug"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: leasing-app-frontend
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: frontend
        env:
        - name: VITE_API_URL
          value: "https://api-dev.yourdomain.com/api"
        resources:
          requests:
            memory: "64Mi"
            cpu: "25m"
          limits:
            memory: "128Mi"
            cpu: "100m"