apiVersion: apps/v1
kind: Deployment
metadata:
  name: leasing-app-backend
  labels:
    app: leasing-app
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: leasing-app
      component: backend
  template:
    metadata:
      labels:
        app: leasing-app
        component: backend
        version: v1
    spec:
      serviceAccountName: leasing-app
      containers:
      - name: backend
        image: your-acr.azurecr.io/leasing-app-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "5000"
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: leasing-app-db-secret
              key: host
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: leasing-app-db-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: leasing-app-db-secret
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: leasing-app-db-secret
              key: database
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: leasing-app-secrets
              key: jwt-secret
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: leasing-app-redis-secret
              key: connection-string
              optional: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/ready
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: leasing-app-frontend
  labels:
    app: leasing-app
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: leasing-app
      component: frontend
  template:
    metadata:
      labels:
        app: leasing-app
        component: frontend
        version: v1
    spec:
      serviceAccountName: leasing-app
      containers:
      - name: frontend
        image: your-acr.azurecr.io/leasing-app-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        env:
        - name: VITE_API_URL
          value: "https://api.yourdomain.com/api"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3