apiVersion: v1
kind: ServiceAccount
metadata:
  name: leasing-app
  labels:
    app: leasing-app
  annotations:
    azure.workload.identity/client-id: "YOUR_MANAGED_IDENTITY_CLIENT_ID"
    azure.workload.identity/tenant-id: "YOUR_TENANT_ID"