apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm-cert-manager
  namespace: cert-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: helm-cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: helm-cert-manager
  namespace: cert-manager
---
apiVersion: batch/v1
kind: Job
metadata:
  name: install-cert-manager
  namespace: cert-manager
spec:
  template:
    spec:
      serviceAccountName: helm-cert-manager
      restartPolicy: Never
      containers:
      - name: helm
        image: alpine/helm:3.13.0
        command:
        - /bin/sh
        - -c
        - |
          helm repo add jetstack https://charts.jetstack.io
          helm repo update
          helm upgrade --install cert-manager jetstack/cert-manager \
            --namespace cert-manager \
            --create-namespace \
            --version v1.13.0 \
            --set installCRDs=true \
            --set resources.requests.cpu=50m \
            --set resources.requests.memory=64Mi \
            --set webhook.resources.requests.cpu=10m \
            --set webhook.resources.requests.memory=32Mi \
            --set cainjector.resources.requests.cpu=10m \
            --set cainjector.resources.requests.memory=32Mi \
            --wait \
            --timeout 5m