# Azure Key Vault Secrets Store CSI Driver SecretProviderClass
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-argocd
  namespace: argocd
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "YOUR_MANAGED_IDENTITY_CLIENT_ID"
    keyvaultName: "YOUR_KEYVAULT_NAME"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: argocd-github-webhook-secret
          objectType: secret
        - |
          objectName: argocd-oidc-client-secret
          objectType: secret
        - |
          objectName: acr-pull-secret
          objectType: secret
    tenantId: "YOUR_TENANT_ID"
  secretObjects:
  - secretName: argocd-secret-keys
    type: Opaque
    data:
    - objectName: argocd-github-webhook-secret
      key: webhook.github.secret
    - objectName: argocd-oidc-client-secret
      key: oidc.azure.clientSecret